import type { KatexHelperItem } from '../../core/editor/helperTypes';

export const katexHelperItems: KatexHelperItem[] = [
  {
    id: 'fraction',
    title: '분수',
    category: '기본',
    keywords: ['분수', 'fraction', 'frac', '나누기'],
    syntax: '\\frac{분자}{분모}',
    example: '\\frac{a+b}{c+d}',
  },
  {
    id: 'power',
    title: '거듭제곱',
    category: '기본',
    keywords: ['제곱', '위첨자', 'power', 'superscript'],
    syntax: 'x^{n}',
    example: 'x^{2}+y^{2}=z^{2}',
  },
  {
    id: 'subscript',
    title: '아래첨자',
    category: '기본',
    keywords: ['아래첨자', 'subscript', 'index'],
    syntax: 'x_{n}',
    example: 'a_{n}=a_{1}+(n-1)d',
  },
  {
    id: 'sqrt',
    title: '제곱근',
    category: '기본',
    keywords: ['루트', '제곱근', 'sqrt', 'root'],
    syntax: '\\sqrt{x}',
    example: '\\sqrt{x^{2}+y^{2}}',
  },
  {
    id: 'times',
    title: '곱하기',
    category: '연산자',
    keywords: ['곱하기', '곱셈', 'times', 'multiply', 'multiplication', '곱'],
    syntax: '\\times',
    example: 'a \\times b',
  },
  {
    id: 'divide',
    title: '나누기',
    category: '연산자',
    keywords: ['나누기', '나눗셈', 'divide', 'division', 'div'],
    syntax: '\\div',
    example: 'a \\div b',
  },
  {
    id: 'plus-minus',
    title: '플러스 마이너스',
    category: '연산자',
    keywords: ['플러스마이너스', 'plus minus', 'pm', '오차'],
    syntax: '\\pm',
    example: 'x = -b \\pm \\sqrt{D}',
  },
  {
    id: 'sum',
    title: '합',
    category: '대형 연산자',
    keywords: ['합', '시그마', 'sum', 'sigma', 'summation'],
    syntax: '\\sum_{i=1}^{n}',
    example: '\\sum_{i=1}^{n} i = \\frac{n(n+1)}{2}',
    displayMode: true,
  },
  {
    id: 'integral',
    title: '적분',
    category: '미적분',
    keywords: ['적분', 'integral', 'int'],
    syntax: '\\int_{a}^{b}',
    example: '\\int_{0}^{1} x^2\\,dx = \\frac{1}{3}',
    displayMode: true,
  },
  {
    id: 'limit',
    title: '극한',
    category: '미적분',
    keywords: ['극한', '리미트', 'limit', 'lim'],
    syntax: '\\lim_{x \\to a}',
    example: '\\lim_{x \\to 0}\\frac{\\sin x}{x}=1',
    displayMode: true,
  },
  {
    id: 'alpha',
    title: '알파',
    category: '그리스 문자',
    keywords: ['알파', 'alpha', 'greek'],
    syntax: '\\alpha',
    example: '\\alpha + \\beta = \\gamma',
  },
  {
    id: 'theta',
    title: '세타',
    category: '그리스 문자',
    keywords: ['세타', 'theta', 'angle', '각도'],
    syntax: '\\theta',
    example: '\\sin \\theta',
  },
  {
    id: 'pi',
    title: '파이',
    category: '그리스 문자',
    keywords: ['파이', 'pi', '원주율'],
    syntax: '\\pi',
    example: 'A=\\pi r^2',
  },
  {
    id: 'matrix',
    title: '행렬',
    category: '행렬',
    keywords: ['행렬', 'matrix', 'pmatrix'],
    syntax: '\\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix}',
    example: '\\begin{pmatrix} 1 & 2 \\\\ 3 & 4 \\end{pmatrix}',
    displayMode: true,
  },
  {
    id: 'cases',
    title: '경우 나누기',
    category: '구조',
    keywords: ['케이스', '경우', 'cases', 'piecewise'],
    syntax: '\\begin{cases} x & x \\ge 0 \\\\ -x & x < 0 \\end{cases}',
    example: '|x| = \\begin{cases} x & x \\ge 0 \\\\ -x & x < 0 \\end{cases}',
    displayMode: true,
  },
  {
    id: 'arrow-right',
    title: '오른쪽 화살표',
    category: '화살표',
    keywords: ['화살표', '오른쪽', 'arrow', 'rightarrow'],
    syntax: '\\rightarrow',
    example: 'A \\rightarrow B',
  },
  {
    id: 'implies',
    title: '따라서/함의',
    category: '논리',
    keywords: ['따라서', '함의', 'implies', 'right arrow', '논리'],
    syntax: '\\Rightarrow',
    example: 'x>0 \\Rightarrow x^2>0',
  },
  {
    id: 'real',
    title: '실수 집합',
    category: '집합',
    keywords: ['실수', 'real', 'set', 'mathbb'],
    syntax: '\\mathbb{R}',
    example: 'x \\in \\mathbb{R}',
  },
  {
    id: 'text',
    title: '수식 안 텍스트',
    category: '텍스트',
    keywords: ['텍스트', '문자', 'text', 'korean'],
    syntax: '\\text{문자}',
    example: 'x = 1 \\quad \\text{일 때}',
  },
];

