import type { MarkdownHelperItem } from '../../core/editor/helperTypes';

export const markdownHelperItems: MarkdownHelperItem[] = [
  {
    id: 'heading-1',
    title: '제목 1',
    category: '제목',
    keywords: ['제목', 'heading', 'h1', 'title'],
    syntax: '# 제목',
    snippet: '# 제목',
    example: '# 제목 1',
  },
  {
    id: 'heading-2',
    title: '제목 2',
    category: '제목',
    keywords: ['제목', 'heading', 'h2', 'subtitle'],
    syntax: '## 제목',
    snippet: '## 제목',
    example: '## 제목 2',
  },
  {
    id: 'heading-3',
    title: '제목 3',
    category: '제목',
    keywords: ['제목', 'heading', 'h3', 'section'],
    syntax: '### 제목',
    snippet: '### 제목',
    example: '### 제목 3',
  },
  {
    id: 'bold',
    title: '볼드',
    category: '강조',
    keywords: ['볼드', '굵게', 'bold', 'strong'],
    syntax: '**텍스트**',
    snippet: '**텍스트**',
    example: '**굵은 텍스트**',
  },
  {
    id: 'italic',
    title: '이탤릭',
    category: '강조',
    keywords: ['이탤릭', '기울임', 'italic', 'emphasis'],
    syntax: '*텍스트*',
    snippet: '*텍스트*',
    example: '*기울인 텍스트*',
  },
  {
    id: 'strike',
    title: '취소선',
    category: '강조',
    keywords: ['취소선', 'strike', 'strikethrough'],
    syntax: '~~텍스트~~',
    snippet: '~~텍스트~~',
    example: '~~취소된 텍스트~~',
  },
  {
    id: 'highlight',
    title: '강조 표시',
    category: '강조',
    keywords: ['형광펜', '하이라이트', 'highlight', 'mark'],
    syntax: '==텍스트==',
    snippet: '==텍스트==',
    example: '==강조 표시==',
  },
  {
    id: 'inline-code',
    title: '인라인 코드',
    category: '코드',
    keywords: ['인라인 코드', 'inline code', 'code'],
    syntax: '`code`',
    snippet: '`code`',
    example: '`const value = 1`',
  },
  {
    id: 'code-block',
    title: '코드 블록',
    category: '코드',
    keywords: ['코드블럭', '코드 블록', 'fence', '```'],
    syntax: '```lang',
    snippet: '```text\n코드\n```',
    example: '```js\nconst value = 1;\n```',
  },
  {
    id: 'quote',
    title: '인용',
    category: '문단',
    keywords: ['인용', 'quote', 'blockquote'],
    syntax: '> 인용문',
    snippet: '> 인용문',
    example: '> 중요한 문장',
  },
  {
    id: 'hard-break',
    title: '줄바꿈',
    category: '문단',
    keywords: ['줄바꿈', 'line break', 'br', 'enter'],
    syntax: '줄 끝 공백 2칸',
    snippet: '  \n',
    example: '첫 줄  \n둘째 줄',
  },
  {
    id: 'indent',
    title: '들여쓰기',
    category: '문단',
    keywords: ['들여쓰기', 'indent', 'tab', 'cmd', 'ctrl'],
    syntax: 'Tab / Cmd+]',
    snippet: '',
    example: '문단\n    들여쓴 줄',
    action: 'indent',
  },
  {
    id: 'outdent',
    title: '내어쓰기',
    category: '문단',
    keywords: ['내어쓰기', 'outdent', 'shift tab', 'cmd', 'ctrl'],
    syntax: 'Shift+Tab / Cmd+[',
    snippet: '',
    example: '문단\n    들여쓴 줄',
    action: 'outdent',
  },
  {
    id: 'horizontal-rule',
    title: '구분선',
    category: '문단',
    keywords: ['구분선', 'divider', 'horizontal rule', 'hr'],
    syntax: '---',
    snippet: '---',
    example: '---',
  },
  {
    id: 'bullet-list',
    title: '불릿 리스트',
    category: '목록',
    keywords: ['불릿', '목록', 'list', 'bullet', 'ul'],
    syntax: '- 항목',
    snippet: '- 항목',
    example: '- 첫 번째\n- 두 번째',
  },
  {
    id: 'numbered-list',
    title: '번호 리스트',
    category: '목록',
    keywords: ['번호', '순서', 'ordered list', 'ol'],
    syntax: '1. 항목',
    snippet: '1. 항목',
    example: '1. 첫 번째\n2. 두 번째',
  },
  {
    id: 'task-list',
    title: '체크리스트',
    category: '목록',
    keywords: ['체크', '할일', 'todo', 'task', 'checkbox'],
    syntax: '- [ ] 할 일',
    snippet: '- [ ] 할 일',
    example: '- [ ] 할 일\n- [x] 완료',
  },
  {
    id: 'link',
    title: '링크',
    category: '링크',
    keywords: ['링크', 'url', 'anchor', 'link'],
    syntax: '[텍스트](URL)',
    snippet: '[텍스트](https://example.com)',
    example: '[Saekim](https://example.com)',
  },
  {
    id: 'image',
    title: '이미지',
    category: '링크',
    keywords: ['이미지', '사진', 'image', 'img', 'asset', 'assets', '원본 경로', '복사'],
    syntax: '![대체텍스트](경로)',
    snippet: '![이미지](image.png)',
    example: '![이미지](image.png)',
  },
  {
    id: 'table',
    title: '표',
    category: '표',
    keywords: ['표', '테이블', 'table'],
    syntax: '| 제목 | 값 |',
    snippet: '| 제목 | 값 |\n| --- | --- |\n| 항목 | 내용 |',
    example: '| 제목 | 값 |\n| --- | --- |\n| 항목 | 내용 |',
  },
  {
    id: 'footnote',
    title: '각주',
    category: '참조',
    keywords: ['각주', 'footnote', 'reference'],
    syntax: '[^1]',
    snippet: '[^1]\n\n[^1]: 각주 내용',
    example: '문장 끝[^1]\n\n[^1]: 각주 내용',
  },
];

